export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export type LOGIN_SUCCESS = typeof LOGIN_SUCCESS;

export const LOGIN_FAILED = 'LOGIN_FAILED';
export type LOGIN_FAILED = typeof LOGIN_FAILED;

export const LOGIN_LOADING = 'LOGIN_LOADING';
export type LOGIN_LOADING = typeof LOGIN_LOADING;

export const LOGIN_PRELOAD_USER = 'LOGIN_PRELOAD_USER';
export type LOGIN_PRELOAD_USER = typeof LOGIN_PRELOAD_USER;